import type { Agent, Manager, Queue, Contact, Recording, Campaign, CallMetric } from '@/types';

// ============================================================
// AGENTS
// ============================================================

export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Aman Verma',
    email: 'aman.verma@callhub.io',
    status: 'online',
    extension: '1001',
    skills: ['Sales', 'Retention', 'Upsell'],
    queues: ['queue-001', 'queue-002'],
    callsHandled: 1247,
    avgHandleTime: 342,
    satisfaction: 94,
    department: 'Sales',
    joinedAt: '2023-03-15',
  },
  {
    id: 'agent-002',
    name: 'Utkarsh Singh',
    email: 'utkarsh.singh@callhub.io',
    status: 'online',
    extension: '1002',
    skills: ['Technical Support', 'Billing', 'Escalations'],
    queues: ['queue-001', 'queue-003'],
    callsHandled: 983,
    avgHandleTime: 418,
    satisfaction: 91,
    department: 'Support',
    joinedAt: '2023-06-20',
  },
  {
    id: 'agent-003',
    name: 'Priya Sharma',
    email: 'priya.sharma@callhub.io',
    status: 'busy',
    extension: '1003',
    skills: ['Customer Success', 'Onboarding'],
    queues: ['queue-002'],
    callsHandled: 1456,
    avgHandleTime: 287,
    satisfaction: 97,
    department: 'Customer Success',
    joinedAt: '2022-11-10',
  },
  {
    id: 'agent-004',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@callhub.io',
    status: 'break',
    extension: '1004',
    skills: ['Sales', 'Demo', 'Lead Qualification'],
    queues: ['queue-001'],
    callsHandled: 762,
    avgHandleTime: 395,
    satisfaction: 88,
    department: 'Sales',
    joinedAt: '2024-01-08',
  },
  {
    id: 'agent-005',
    name: 'Sneha Patel',
    email: 'sneha.patel@callhub.io',
    status: 'offline',
    extension: '1005',
    skills: ['Billing', 'Compliance', 'Retention'],
    queues: ['queue-003'],
    callsHandled: 2103,
    avgHandleTime: 264,
    satisfaction: 96,
    department: 'Billing',
    joinedAt: '2022-04-22',
  },
  {
    id: 'agent-006',
    name: 'Karan Joshi',
    email: 'karan.joshi@callhub.io',
    status: 'online',
    extension: '1006',
    skills: ['Technical Support', 'Network', 'Escalations'],
    queues: ['queue-003', 'queue-004'],
    callsHandled: 671,
    avgHandleTime: 487,
    satisfaction: 85,
    department: 'Support',
    joinedAt: '2024-03-11',
  },
  {
    id: 'agent-007',
    name: 'Divya Nair',
    email: 'divya.nair@callhub.io',
    status: 'online',
    extension: '1007',
    skills: ['Customer Success', 'Upsell', 'Renewals'],
    queues: ['queue-002', 'queue-004'],
    callsHandled: 1891,
    avgHandleTime: 312,
    satisfaction: 93,
    department: 'Customer Success',
    joinedAt: '2022-09-05',
  },
  {
    id: 'agent-008',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@callhub.io',
    status: 'busy',
    extension: '1008',
    skills: ['Sales', 'Enterprise', 'Negotiation'],
    queues: ['queue-001'],
    callsHandled: 534,
    avgHandleTime: 523,
    satisfaction: 90,
    department: 'Sales',
    joinedAt: '2024-07-01',
  },
];

// ============================================================
// MANAGERS
// ============================================================

export const mockManagers: Manager[] = [
  {
    id: 'mgr-001',
    name: 'Vikram Khanna',
    email: 'vikram.khanna@callhub.io',
    department: 'Sales',
    agentsManaged: 12,
    phone: '+91 98100 44321',
    role: 'Sales Manager',
    joinedAt: '2021-02-14',
  },
  {
    id: 'mgr-002',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@callhub.io',
    department: 'Support',
    agentsManaged: 18,
    phone: '+91 98200 55432',
    role: 'Support Lead',
    joinedAt: '2020-08-22',
  },
  {
    id: 'mgr-003',
    name: 'Rohan Desai',
    email: 'rohan.desai@callhub.io',
    department: 'Operations',
    agentsManaged: 25,
    phone: '+91 98300 66543',
    role: 'Operations Director',
    joinedAt: '2019-05-10',
  },
  {
    id: 'mgr-004',
    name: 'Meera Bhat',
    email: 'meera.bhat@callhub.io',
    department: 'Customer Success',
    agentsManaged: 9,
    phone: '+91 98400 77654',
    role: 'CS Manager',
    joinedAt: '2022-01-18',
  },
  {
    id: 'mgr-005',
    name: 'Siddharth Roy',
    email: 'siddharth.roy@callhub.io',
    department: 'Quality',
    agentsManaged: 6,
    phone: '+91 98500 88765',
    role: 'QA Manager',
    joinedAt: '2021-11-03',
  },
];

// ============================================================
// QUEUES
// ============================================================

export const mockQueues: Queue[] = [
  {
    id: 'queue-001',
    name: 'Sales',
    strategy: 'Least Recent',
    ringTime: 30,
    wrapUpTime: 60,
    status: 'active',
    agents: ['agent-001', 'agent-002', 'agent-004', 'agent-008'],
    maxWaitTime: 120,
    musicOnHold: 'corporate-01.mp3',
    priority: 1,
    description: 'Primary inbound sales queue for new customer acquisition',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-06-10T14:30:00Z',
  },
  {
    id: 'queue-002',
    name: 'Customer Success',
    strategy: 'Round Robin',
    ringTime: 25,
    wrapUpTime: 45,
    status: 'active',
    agents: ['agent-003', 'agent-007'],
    maxWaitTime: 90,
    musicOnHold: 'ambient-02.mp3',
    priority: 2,
    description: 'Dedicated queue for customer success and onboarding calls',
    createdAt: '2023-02-20T10:00:00Z',
    updatedAt: '2024-06-12T11:15:00Z',
  },
  {
    id: 'queue-003',
    name: 'Technical Support',
    strategy: 'Fewest Calls',
    ringTime: 40,
    wrapUpTime: 90,
    status: 'active',
    agents: ['agent-002', 'agent-005', 'agent-006'],
    maxWaitTime: 180,
    musicOnHold: 'hold-03.mp3',
    priority: 1,
    description: 'Level 1 and Level 2 technical support queue',
    createdAt: '2023-01-20T08:00:00Z',
    updatedAt: '2024-06-11T16:45:00Z',
  },
  {
    id: 'queue-004',
    name: 'Billing',
    strategy: 'Ring All',
    ringTime: 20,
    wrapUpTime: 30,
    status: 'active',
    agents: ['agent-006', 'agent-007'],
    maxWaitTime: 60,
    musicOnHold: 'corporate-01.mp3',
    priority: 3,
    description: 'Billing inquiries, payment issues and refund requests',
    createdAt: '2023-03-05T09:30:00Z',
    updatedAt: '2024-06-09T09:20:00Z',
  },
  {
    id: 'queue-005',
    name: 'Enterprise',
    strategy: 'Linear Hunt',
    ringTime: 45,
    wrapUpTime: 120,
    status: 'paused',
    agents: ['agent-001', 'agent-008'],
    maxWaitTime: 240,
    musicOnHold: 'enterprise-04.mp3',
    priority: 1,
    description: 'Dedicated queue for enterprise tier accounts',
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-05-28T13:00:00Z',
  },
];

// ============================================================
// CONTACTS
// ============================================================

export const mockContacts: Contact[] = [
  {
    id: 'contact-001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@techcorp.in',
    phone: '+91 98765 43210',
    company: 'TechCorp India Pvt. Ltd.',
    status: 'active',
    tags: ['Enterprise', 'Priority'],
    lastContact: '2024-06-14T10:30:00Z',
    totalCalls: 23,
    notes: 'Key enterprise contact. Prefers calls after 11 AM.',
    createdAt: '2023-01-10T08:00:00Z',
  },
  {
    id: 'contact-002',
    name: 'Sunita Sharma',
    email: 'sunita@startuphive.co',
    phone: '+91 97654 32109',
    company: 'StartupHive Co.',
    status: 'active',
    tags: ['SMB', 'Upsell Candidate'],
    lastContact: '2024-06-13T14:15:00Z',
    totalCalls: 8,
    notes: 'Interested in upgrading to Pro plan.',
    createdAt: '2023-08-22T09:00:00Z',
  },
  {
    id: 'contact-003',
    name: 'Aditya Birla',
    email: 'aditya.birla@globalfinance.com',
    phone: '+91 96543 21098',
    company: 'Global Finance Ltd.',
    status: 'active',
    tags: ['Enterprise', 'Financial'],
    lastContact: '2024-06-12T11:00:00Z',
    totalCalls: 47,
    notes: 'Long-term client. Requires compliance documentation.',
    createdAt: '2022-03-15T10:00:00Z',
  },
  {
    id: 'contact-004',
    name: 'Pooja Mehta',
    email: 'pooja@retailplus.in',
    phone: '+91 95432 10987',
    company: 'RetailPlus India',
    status: 'active',
    tags: ['Retail', 'New'],
    lastContact: '2024-06-11T16:30:00Z',
    totalCalls: 3,
    notes: 'New contact. Evaluating our solution.',
    createdAt: '2024-05-01T08:00:00Z',
  },
  {
    id: 'contact-005',
    name: 'Aryan Gupta',
    email: 'aryan@cloudsync.io',
    phone: '+91 94321 09876',
    company: 'CloudSync Technologies',
    status: 'inactive',
    tags: ['SaaS', 'Churned'],
    lastContact: '2024-03-10T10:00:00Z',
    totalCalls: 15,
    notes: 'Churned due to pricing. Re-engagement candidate.',
    createdAt: '2022-11-08T09:00:00Z',
  },
  {
    id: 'contact-006',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@ecommerce.in',
    phone: '+91 93210 98765',
    company: 'QuickCart Ecommerce',
    status: 'active',
    tags: ['Ecommerce', 'Growth'],
    lastContact: '2024-06-14T09:00:00Z',
    totalCalls: 12,
    notes: 'Fast-growing account. Needs dedicated support.',
    createdAt: '2023-07-19T09:00:00Z',
  },
  {
    id: 'contact-007',
    name: 'Nikhil Bansal',
    email: 'nikhil@healthtech.in',
    phone: '+91 92109 87654',
    company: 'HealthTech Solutions',
    status: 'blocked',
    tags: ['Healthcare', 'DNC'],
    lastContact: '2024-01-05T11:00:00Z',
    totalCalls: 2,
    notes: 'Requested DNC. Do not contact.',
    createdAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'contact-008',
    name: 'Lakshmi Devi',
    email: 'lakshmi@infratech.co',
    phone: '+91 91098 76543',
    company: 'InfraTech Corp.',
    status: 'active',
    tags: ['Infrastructure', 'Annual'],
    lastContact: '2024-06-13T15:45:00Z',
    totalCalls: 31,
    notes: 'Annual contract. Renewal due in September.',
    createdAt: '2022-08-30T09:00:00Z',
  },
];

// ============================================================
// RECORDINGS
// ============================================================

export const mockRecordings: Recording[] = [
  {
    id: 'rec-001',
    contactName: 'Rajesh Kumar',
    agentName: 'Aman Verma',
    queueName: 'Sales',
    duration: 487,
    date: '2024-06-14T10:30:00Z',
    type: 'inbound',
    sentiment: 'positive',
    transcriptAvailable: true,
    size: 9741248,
    callId: 'CALL-20240614-001',
  },
  {
    id: 'rec-002',
    contactName: 'Sunita Sharma',
    agentName: 'Priya Sharma',
    queueName: 'Customer Success',
    duration: 312,
    date: '2024-06-14T14:15:00Z',
    type: 'inbound',
    sentiment: 'positive',
    transcriptAvailable: true,
    size: 6234112,
    callId: 'CALL-20240614-002',
  },
  {
    id: 'rec-003',
    contactName: 'Aryan Gupta',
    agentName: 'Karan Joshi',
    queueName: 'Technical Support',
    duration: 891,
    date: '2024-06-14T11:00:00Z',
    type: 'inbound',
    sentiment: 'negative',
    transcriptAvailable: false,
    size: 17825792,
    callId: 'CALL-20240614-003',
  },
  {
    id: 'rec-004',
    contactName: 'Pooja Mehta',
    agentName: 'Rahul Mehta',
    queueName: 'Sales',
    duration: 234,
    date: '2024-06-14T09:45:00Z',
    type: 'outbound',
    sentiment: 'neutral',
    transcriptAvailable: true,
    size: 4677632,
    callId: 'CALL-20240614-004',
  },
  {
    id: 'rec-005',
    contactName: 'Kavya Reddy',
    agentName: 'Divya Nair',
    queueName: 'Customer Success',
    duration: 643,
    date: '2024-06-14T09:00:00Z',
    type: 'inbound',
    sentiment: 'positive',
    transcriptAvailable: true,
    size: 12861440,
    callId: 'CALL-20240614-005',
  },
  {
    id: 'rec-006',
    contactName: 'Aditya Birla',
    agentName: 'Aman Verma',
    queueName: 'Enterprise',
    duration: 1247,
    date: '2024-06-13T16:00:00Z',
    type: 'inbound',
    sentiment: 'positive',
    transcriptAvailable: true,
    size: 24944640,
    callId: 'CALL-20240613-001',
  },
  {
    id: 'rec-007',
    contactName: 'Nikhil Bansal',
    agentName: 'Sneha Patel',
    queueName: 'Billing',
    duration: 178,
    date: '2024-06-13T14:30:00Z',
    type: 'inbound',
    sentiment: 'negative',
    transcriptAvailable: false,
    size: 3563520,
    callId: 'CALL-20240613-002',
  },
  {
    id: 'rec-008',
    contactName: 'Lakshmi Devi',
    agentName: 'Utkarsh Singh',
    queueName: 'Technical Support',
    duration: 752,
    date: '2024-06-13T11:15:00Z',
    type: 'inbound',
    sentiment: 'neutral',
    transcriptAvailable: true,
    size: 15040512,
    callId: 'CALL-20240613-003',
  },
];

// ============================================================
// CALL METRICS (last 14 days)
// ============================================================

export const mockCallMetrics: CallMetric[] = Array.from({ length: 14 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (13 - i));
  const totalCalls = Math.floor(Math.random() * 200 + 300);
  const answeredCalls = Math.floor(totalCalls * (0.82 + Math.random() * 0.12));
  return {
    date: date.toISOString().split('T')[0],
    totalCalls,
    answeredCalls,
    missedCalls: totalCalls - answeredCalls,
    avgHandleTime: Math.floor(Math.random() * 120 + 280),
    avgWaitTime: Math.floor(Math.random() * 60 + 20),
    satisfaction: Math.floor(Math.random() * 15 + 82),
    firstCallResolution: Math.floor(Math.random() * 20 + 68),
  };
});

// ============================================================
// CAMPAIGNS
// ============================================================

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Q3 Enterprise Outreach',
    type: 'outbound',
    status: 'running',
    startDate: '2024-06-01',
    endDate: '2024-06-30',
    targetCalls: 500,
    completedCalls: 287,
    agents: ['agent-001', 'agent-004', 'agent-008'],
    queue: 'queue-001',
  },
  {
    id: 'camp-002',
    name: 'Customer Satisfaction Survey',
    type: 'outbound',
    status: 'running',
    startDate: '2024-06-10',
    endDate: '2024-06-25',
    targetCalls: 200,
    completedCalls: 143,
    agents: ['agent-003', 'agent-007'],
    queue: 'queue-002',
  },
  {
    id: 'camp-003',
    name: 'Churn Prevention',
    type: 'outbound',
    status: 'paused',
    startDate: '2024-05-15',
    endDate: '2024-06-15',
    targetCalls: 150,
    completedCalls: 98,
    agents: ['agent-001', 'agent-003'],
    queue: 'queue-002',
  },
  {
    id: 'camp-004',
    name: 'Summer Promotion 2024',
    type: 'blended',
    status: 'draft',
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    targetCalls: 800,
    completedCalls: 0,
    agents: [],
    queue: 'queue-001',
  },
];

// ============================================================
// DASHBOARD SUMMARY (live stats)
// ============================================================

export const mockDashboardStats = {
  totalCallsToday: 487,
  callsInQueue: 12,
  agentsAvailable: 6,
  agentsBusy: 9,
  avgWaitTime: 34, // seconds
  avgHandleTime: 362, // seconds
  satisfactionScore: 91.4,
  firstCallResolution: 74.2,
  callsThisWeek: 2847,
  callsLastWeek: 2631,
  missedCallsToday: 23,
  abandonmentRate: 4.7,
  peakHour: '11:00 AM',
  topQueue: 'Technical Support',
  topAgent: 'Priya Sharma',
};

// ============================================================
// SAVED PROMPTS
// ============================================================

export const mockSavedPrompts = [
  { id: 'sp-001', label: 'Today\'s recordings', prompt: 'Show today\'s call recordings', category: 'Recordings' },
  { id: 'sp-002', label: 'Weekly report', prompt: 'Generate weekly performance report', category: 'Reports' },
  { id: 'sp-003', label: 'Dashboard overview', prompt: 'Show me today\'s call center dashboard', category: 'Dashboard' },
  { id: 'sp-004', label: 'All queues', prompt: 'Show all call queues', category: 'Queues' },
  { id: 'sp-005', label: 'All agents', prompt: 'Show all agents', category: 'Contacts' },
  { id: 'sp-006', label: 'IVR builder', prompt: 'Create IVR for customer support', category: 'IVR' },
];
